config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'

  #home routes
  get 'home', to: 'home#index'
  get 'about', to: 'home#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block", class:"form-label" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, style: "display: block", class:"form-label" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, style: "display: block", class:"form-label" %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit class:"btn btn-primary mt-2"%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <div class="h-100 p-5 bg-light border rounded-3">
    <h2><%= friend.first_name %> <%= friend.last_name %></h2>
    <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
    <button class="btn btn-outline-secondary" type="button">Example button</button>
  </div>
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<div class="mt-3">
  <%= link_to "Show this friend", @friend,class:"btn btn-success" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<h1>Friend List</h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
    </tr>
    </thead>

    <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= link_to friend.first_name + " " + friend.last_name, friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>


<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<br>

<%= render "form", friend: @friend %>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark mt-3" %>
</div>

app/views/friends/show.html.erb
<div id="<%= dom_id @friend %>">
  <div class="h-100 p-5 bg-light border rounded-3">
    <h2><%= @friend.first_name %> <%= @friend.last_name %></h2>
    <p>
      <%= @friend.email %>  |  <%= @friend.phone %>   |  <%= @friend.twitter %>
    </p>
    <br/>
    <hr>
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %>
    <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>

    <%= button_to "Destroy this friend", @friend, :class=>"btn btn-danger mt-3", method: :delete %>
  </div>

</div>

<div>



</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', home_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Friends', friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'New Friend', new_friend_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { 'turbo-method': :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Home world</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friends App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>

<body>

<%= render 'home/header' %>
<div class="container">
  <br/>

  <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>

  <%= yield %>
</div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>